# CDUC VERSION 1
:toc: left
:toc-title: Table des matières

## Contexte du projet
Pour s’adapter aux exigences d’instantanéité de leurs clients, les banques françaises ont accentué leurs efforts de restructuration et leurs investissements dans le digital. Des chantiers longs et coûteux. Par exemple, la Banque Postale a indiqué que sa banque mobile baptisée Ma French Bank sera disponible dans les bureaux de Poste au printemps 2019. Mais les banques ne se contentent pas de créer des offres alternatives : elles rénovent aussi en profondeur leurs services de banque au quotidien.
Au sein des réseaux de banque de détail, cela se traduit par des investissements majeurs dans la modernisation des outils de bureautique des guichetiers, et dans la robotisation des tâches automatisables. Un exercice qui s’accompagne de restructurations et, dans certains cas, d’une refonte du réseau.

Ainsi, le modèle organisationnel de BNP Paribas, basé sur une structure historique hiérarchique, vit actuellement une petite révolution, alors qu’il évolue vers une approche transversale et pluridisciplinaire. "De la phase de la simulation d’un emprunt à la signature de l’acte définitif chez le notaire, il faut que nous puissions suivre notre client sans interruption et que nous sachions (tout comme lui) en permanence où il en est", décrit Sophie Heller (directeur des opérations). Les équipes seront ainsi réparties en fonction de parcours clients – achat d’un bien, projet d’investissement ou de retraite, succession… Pour chacun de ces "projets de vie", des professionnels de diverses disciplines (marketeurs, développeurs, designers mais aussi des fonctions "juridiques" ou "risque") interagissent pour développer les parcours et les trajectoires de chaque client, captées, traitées, mises à jour et accessibles par tous en temps réel. "Cela nécessite de profonds changements culturels et organisationnels, en plus d’une nouvelle architecture IT", évalue Sophie Heller.

Sources :

* Les échos février 2018 : Banques, des restructurations menées tambour battant

* JDN Février 2018 : BNP Paribas accélère sa transformation digitale

# Sujet
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. Vous travaillerez à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque.

## Version Originale

## Version à développer

## Contraintes

