# DOCUMENTATION UTILISATEUR VERSION 1
:toc: left
:toc-title: Table des matières
:icons: font
:nofooter:

## Présentation générale

### Contexte 

Pour s’adapter aux exigences d’instantanéité de leurs clients, les banques françaises ont accentué leurs efforts de restructuration et leurs investissements dans le digital. Des chantiers longs et coûteux. Elles ne se contentent pas de créer des offres alternatives : elles rénovent aussi en profondeur leurs services de banque au quotidien. +
Le réseaux de bancaire Dailybank possèdent plusieurs outils qui deviennent obsolètes et une première version d’application qui nécessite une refonte. Les besoins de la banque ont évolués, tout comme ceux de leurs clients, il faut donc développer plusieurs fonctionnalités pour répondre à ces nouveaux besoins.

### Objectifs de l'application

L’objectif recherché par la banque DailyBank est de développer une application Java-Oracle de gestion de comptes, pour remplacer plusieurs outils obsolètes.
Pour ce faire, une première version est mise à dispotion "DailyBank" qu’il faudra adapter aux nouveaux besoins.
Ces nouveaux besoins sont :

* Elle doit permettre de gérer des comptes bancaires de dépôt pour des clients créés

* Elle doit permettre de débiter et de créditer un compte de deux manières différentes :

** Par échange d’argent entre deux comptes distincts domiciliés dans le même réseau bancaire

** Par personne physique se présentant devant un guichet

## Installation de l'application

Pour pouvoir lancer l'application, l'installation de Java en version 1.8 est nécessaire.
Pour ce faire, vous devez  suivre ces étapes : 

* Télécharger gratuitement la version 1.8 de Java sur le https://www.java.com/fr/download/[site d'Oracle]
** Vous pouvez au préalable vérifiez que l'installation c'est bien réaliser (depuis un terminal) :

    $ java -version 

Ensuite lancer le fichier .jar depuis un terminal (si il ne s'ouvre par en double cliquant dessus) :

(depuis un terminal) :

    $ cd '.\Desktop\DailyBank workspace\'
    $ java -jar Dailybank.jar



## Utilisation de l'application

Deux utilisateurs distincts peuvent être constaté, ils sont le guichetier et le chef d'agence. En plus des fonctionnalités qu'ont les guichetier qui sont :

* Modifier les informations des clients (adresse, téléphone, …)
* Créer de nouveaux clients
* Consulter un compte
* Créditer/débiter un compte (java et BD avec procédure stockée)
* Créer un compte
* Effectuer un virement de compte à compte
* Clôturer un compte

les chef d'agence peuvent :

* Gérer (faire le « CRUD ») les employés (guichetier et chef d’agence)

## Fonctionnement de l'application

*Création d'un compte bancaire (développer par Christopher)*

NOTE: Accessible depuis la fenêtre gestion des comptes

En cliquant sur le bouton « nouveau compte » une fenêtre de création de compte s'ouvrira.
L'utilisateur pourra créer un nouveau compte pour le client en entrant les informations : 

* Découvert autorisé 
* solde (premier dépôt)    

En cliquant sur le bouton « ajouter », cela aura pour action d'ajouter le nouveau compte du client dans la base de données et en cliquant sur le bouton « annuler », cela aura pour action d'annuler l'ajout de ce nouveau compte.

*Clôturation d'un compte bancaire (développer par Ruben)*

NOTE: Accessible depuis la fenêtre gestion des comptes

En cliquant sur le bouton « supprimer compte » une fenêtre de confirmation s'ouvrira demandant à l'utilisateur de confirmer sa demande. +
En cliquant sur le bouton « confirmer » le compte sera clôturer et en cliquant sur le bouton « annuler » le compte ne sera pas clôturer.

NOTE: Un compte clôturer sera toujours visible, mais plus aucune actions ne sera possible à moins de le rendre actif

*Enregistrer un débit (développer par Yann)*

NOTE: Accessible depuis la fenêtre gestion des opérations

En cliquant sur le bouton « enregistrer débit » une fenêtre d'enregistrement d'un débit s'ouvre.
L'utilisateur pourra enregistrer un débit pour un client en séléctionnant :

* Le type d'opération
* Le montant de l'opération

WARNING: Le montant de débit ne doit pas être supérieur au montant du découvert autorisé du client

*Enregistrer un crédit (développer par Yann)*

NOTE: Accessible depuis la fenêtre gestion des opérations

En cliquant sur le bouton « enregistrer crédit » une fenêtre d'enregistrement d'un crédit s'ouvre.
L'utilisateur pourra enregistrer un crédit pour un client en séléctionnant :

* Le type d'opération
* Le montant de l'opération

*Enregistrer un virement (développer par Christopher)*

NOTE: Accessible depuis la fenêtre gestion des opérations

En cliquant sur le bouton « enregistrer virement » une fenêtre d'enregistrement d'un virement s'ouvre.
L'utilisateur pourra enregistrer un virement pour un client en séléctionnant :

* Le montant de l'opération
* Le compte qui effectuent le virement
* Le compte qui reçoit le virement

WARNING: Le montant du virement ne doit pas être supérieur au montant du découvert autorisé du compte +
         Le numéro de compte qui reçoit le virement doit être correct + 
         Le numéro de compte qui effectuent le virement doit être correct

*Gestion du CRUD*
