# DOCUMENTATION UTILISATEUR VERSION 0
:toc: left
:toc-title: Table des matières
:icons: font
:nofooter:

## Présentation générale

### Contexte 

Pour s’adapter aux exigences d’instantanéité de leurs clients, les banques françaises ont accentué leurs efforts de restructuration et leurs investissements dans le digital. Des chantiers longs et coûteux. Elles ne se contentent pas de créer des offres alternatives : elles rénovent aussi en profondeur leurs services de banque au quotidien. +
Le réseaux de bancaire Dailybank possèdent plusieurs outils qui deviennent obsolètes et une première version d’application qui nécessite une refonte. Les besoins de la banque ont évolués, tout comme ceux de leurs clients, il faut donc développer plusieurs fonctionnalités pour répondre à ces nouveaux besoins.

### Objectifs de l'application

L’objectif recherché par la banque DailyBank est de développer une application Java-Oracle de gestion de comptes, pour remplacer plusieurs outils obsolètes.
Pour ce faire, une première version est mise à dispotion "DailyBank" qu’il faudra adapter aux nouveaux besoins.
Ces nouveaux besoins sont :

* Elle doit permettre de gérer des comptes bancaires de dépôt pour des clients créés

* Elle doit permettre de débiter et de créditer un compte de deux manières différentes :

** Par échange d’argent entre deux comptes distincts domiciliés dans le même réseau bancaire

** Par personne physique se présentant devant un guichet

## Installation de l'application

Pour pouvoir lancer l'application, l'installation de Java en version 1.8 est nécessaire.
Pour ce faire, vous devez  suivre ces étapes : 

* Télécharger gratuitement la version 1.8 de Java sur le https://www.java.com/fr/download/[site d'Oracle]
** Vous pouvez au préalable vérifiez que l'installation c'est bien réaliser (depuis un terminal) :

    $ java -version 

Ensuite lancer le fichier .jar depuis un terminal (si il ne s'ouvre par en double cliquant dessus) :

(depuis un terminal) :

    $ cd '.\Desktop\DailyBank workspace\'
    $ java -jar Dailybank.jar



## Utilisation de l'application

Deux utilisateurs distincts peuvent être constaté, ils sont le guichetier et le chef d'agence. En plus des fonctionnalités qu'ont les guichetier qui sont :

* débiter un compte (java et BD avec procédure stockée)

* Créer un compte

* Effectuer un virement de compte à compte

* Clôturer un compte

les chef d'agence peuvent :

Gérer (faire le « CRUD ») les employés (guichetier et chef d’agence)

## Fonctionnement de l'application

### Utilisateur : Guichetier

#### Fenêtre gestion clients 

*Désactivation d'un client*

#### Fenêtre gestion des comptes

*modification d'un compte*

*clôturation d'un compte*

*création d'un nouveau compte*

#### Fenêtre gestion des opérations

*enregistrer un débit*

*enregistrer un crédit*

*réaliser un virement*

### utilisateur : Chef D'agence



## Résultats et production de l'application